# Prefix
set -g prefix C-s
unbind C-b
# Mouse
set -g mouse on
set -g mode-keys vi

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1

# change the position of the status bar
set-option -g status-position top

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

#set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...
#set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'TanglingTreats/tmux-everforest' # Adds to the list of plugins
set -g @tmux-everforest 'dark-medium' # Sets the option to select the theme. Also the default.


# Reload tmux configuration with Ctrl-S, r
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

